# Generated by Django 5.2.5 on 2025-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Provide your age if you want.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_travel_style',
            field=models.CharField(blank=True, choices=[('budget', 'Budget'), ('luxury', 'Luxury'), ('adventure', 'Adventure'), ('family', 'Family'), ('solo', 'Solo')], help_text='Optional. Choose your preferred travel style.', max_length=50, null=True),
        ),
    ]
