# Generated by Django 5.2.5 on 2025-08-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_travel_style',
            field=models.CharField(blank=True, choices=[('budget', 'Budget'), ('luxury', 'Luxury'), ('adventure', 'Adventure'), ('family', 'Family'), ('solo', 'Solo')], max_length=50, null=True),
        ),
    ]
